"""Pipeline data models for PTCV-24/PTCV-60 end-to-end orchestration.

PipelineResult carries all stage outputs and the lineage chain
sha256 values needed to verify ALCOA++ traceability from protocol
download through validated SDTM package.

Risk tier: MEDIUM — data pipeline orchestration models (no patient data).

Regulatory references:
- ALCOA++ Traceable: sha256 chain from protocol_sha256 through each stage
- ALCOA++ Original: each stage has its own run_id; pipeline_run_id groups
  the seven lightweight stage-checkpoint lineage records
"""

from __future__ import annotations

import dataclasses
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ..extraction.models import ExtractionResult
    from ..ich_parser.classification_router import CascadeResult
    from ..ich_parser.coverage_reviewer import CoverageResult
    from ..ich_parser.llm_retemplater import RetemplatingResult
    from ..ich_parser.parser import ParseResult
    from ..soa_extractor.models import ExtractResult
    from ..sdtm.models import SdtmGenerationResult
    from ..sdtm.validation.models import ValidationResult
    from ..ich_parser.fidelity_checker import FidelityResult


# Expected pipeline stage names (in order) — PTCV-60/PTCV-161 reordering
PIPELINE_STAGES = [
    "download",
    "extraction",
    "soa_extraction",
    "classification_cascade",
    "retemplating",
    "coverage_review",
    "sdtm_generation",
    "validation",
]


@dataclasses.dataclass
class StageCheckpoint:
    """Lightweight pipeline-level record written after each stage completes.

    Written to StorageGateway under the orchestrator's pipeline_run_id so
    that get_lineage(pipeline_run_id) returns exactly one record per stage.

    Attributes:
        stage: Pipeline stage name (one of PIPELINE_STAGES).
        stage_run_id: The run_id generated by the stage service.
        artifact_key: Primary artifact key produced by this stage.
        artifact_sha256: SHA-256 of the primary artifact.
        source_sha256: SHA-256 of the prior stage's primary artifact.
    """

    stage: str
    stage_run_id: str
    artifact_key: str
    artifact_sha256: str
    source_sha256: str


@dataclasses.dataclass
class LineageChainVerification:
    """Result of verifying the sha256 chain across all pipeline stages.

    Attributes:
        is_valid: True when every stage's source_sha256 matches the prior
            stage's artifact_sha256.
        stages_verified: Number of stage links verified.
        broken_at_stage: Name of the first stage where the chain breaks,
            or None if the chain is intact.
        details: Human-readable verification notes per stage.
    """

    is_valid: bool
    stages_verified: int
    broken_at_stage: Optional[str]
    details: list[str]


@dataclasses.dataclass
class PipelineResult:
    """End-to-end pipeline execution result for one protocol amendment.

    Carries the outputs from all 7 stages plus a lineage chain summary
    traceable from protocol download to validation report.

    PTCV-60 pipeline order:
        download → extraction → soa_extraction → retemplating →
        coverage_review → sdtm_generation → validation

    Attributes:
        pipeline_run_id: UUID4 assigned by the orchestrator. Used as the
            run_id for the seven stage-checkpoint lineage records.
        registry_id: Trial registry identifier.
        amendment_number: Protocol amendment version (e.g. "00").

        extraction_result: Output from PTCV-19 ExtractionService.
        soa_result: Output from PTCV-21 SoaExtractor.
        retemplating_result: Output from PTCV-60 LlmRetemplater.
        coverage_result: Output from PTCV-60 CoverageReviewer.
        sdtm_result: Output from PTCV-22 SdtmService.
        validation_result: Output from PTCV-23 ValidationService.
        fidelity_result: Output from PTCV-65 FidelityChecker (opt-in).

        parse_result: Deprecated alias — kept for backward compat.
            Use retemplating_result instead.

        protocol_sha256: SHA-256 of the input protocol file (PTCV-18).
        stage_checkpoints: Ordered list of stage checkpoints.
        pipeline_timestamp_utc: ISO 8601 UTC timestamp of run start.
    """

    pipeline_run_id: str
    registry_id: str
    amendment_number: str

    extraction_result: Optional["ExtractionResult"]
    soa_result: Optional["ExtractResult"]
    retemplating_result: Optional["RetemplatingResult"]
    coverage_result: Optional["CoverageResult"]
    sdtm_result: Optional["SdtmGenerationResult"]
    validation_result: Optional["ValidationResult"]

    protocol_sha256: str
    stage_checkpoints: list[StageCheckpoint]
    pipeline_timestamp_utc: str

    # Deprecated: kept for backward compatibility
    parse_result: Optional["ParseResult"] = None

    # PTCV-65: Optional fidelity check result (opt-in stage)
    fidelity_result: Optional["FidelityResult"] = None

    # PTCV-161: Classification cascade result (enabled by default)
    cascade_result: Optional["CascadeResult"] = None

    # PTCV-163: Degradation chain metadata
    extraction_method: str = ""      # e.g. "E3:pdfplumber"
    classification_method: str = ""  # e.g. "C2:neobert_sonnet"

    def verify_lineage_chain(self) -> LineageChainVerification:
        """Verify that sha256 values form an unbroken chain across stages.

        Returns:
            LineageChainVerification with is_valid=True when every stage's
            source_sha256 matches the prior stage's artifact_sha256.
        [PTCV-24 Scenario: Unbroken ALCOA++ lineage chain]
        """
        if not self.stage_checkpoints:
            return LineageChainVerification(
                is_valid=False,
                stages_verified=0,
                broken_at_stage=None,
                details=["No stage checkpoints recorded"],
            )

        details: list[str] = []
        prior_sha = self.protocol_sha256

        for cp in self.stage_checkpoints:
            if cp.stage == "download":
                # Download stage uses the input protocol_sha256
                prior_sha = cp.artifact_sha256
                details.append(f"  ✓ download: sha256={cp.artifact_sha256[:16]}…")
                continue

            if cp.source_sha256 != prior_sha:
                details.append(
                    f"  ✗ {cp.stage}: source_sha256 mismatch — "
                    f"expected {prior_sha[:16]}… got {cp.source_sha256[:16]}…"
                )
                return LineageChainVerification(
                    is_valid=False,
                    stages_verified=self.stage_checkpoints.index(cp),
                    broken_at_stage=cp.stage,
                    details=details,
                )

            details.append(
                f"  ✓ {cp.stage}: sha256={cp.artifact_sha256[:16]}… "
                f"← source={cp.source_sha256[:16]}…"
            )
            prior_sha = cp.artifact_sha256

        return LineageChainVerification(
            is_valid=True,
            stages_verified=len(self.stage_checkpoints),
            broken_at_stage=None,
            details=details,
        )

    @property
    def all_stages_complete(self) -> bool:
        """True when all 7 pipeline stages completed successfully."""
        return (
            self.extraction_result is not None
            and self.soa_result is not None
            and self.retemplating_result is not None
            and self.coverage_result is not None
            and self.sdtm_result is not None
            and self.validation_result is not None
        )

    @property
    def stage_names_present(self) -> set[str]:
        """Set of stage names recorded in stage_checkpoints."""
        return {cp.stage for cp in self.stage_checkpoints}
