"""Vision API captioning for detected visual elements (PTCV-226).

Sends cropped figure images to Claude Sonnet Vision API with
domain-specific prompts to generate machine-readable captions.
Batches multiple figures per page into a single API call to
reduce token cost.

Gracefully degrades when ANTHROPIC_API_KEY is not set —
figures get empty captions but no error is raised.

Risk tier: MEDIUM — LLM API call, no patient data.
"""

from __future__ import annotations

import base64
import json
import logging
import os
from dataclasses import dataclass, field
from typing import Any, Optional

from .figure_detector import DetectedFigure, crop_figure_image

logger = logging.getLogger(__name__)

_DEFAULT_MODEL = "claude-sonnet-4-6"
_MAX_TOKENS = 2048


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class FigureCaption:
    """Caption generated by Vision API for a detected figure.

    Attributes:
        figure: The detected figure this caption belongs to.
        caption: Machine-generated description of the figure.
        caption_model: Model used for captioning.
        token_cost: Input + output tokens for this caption.
        from_existing: True if caption was from figure's own caption
            field (no API call needed).
    """

    figure: DetectedFigure
    caption: str = ""
    caption_model: str = ""
    token_cost: int = 0
    from_existing: bool = False

    @property
    def has_caption(self) -> bool:
        """Whether a non-empty caption exists."""
        return bool(self.caption.strip())


@dataclass
class CaptionResult:
    """Result of captioning all figures in a PDF.

    Attributes:
        captions: List of FigureCaption objects.
        total_token_cost: Sum of all API call token costs.
        api_calls_made: Number of Vision API calls.
        figures_captioned: Number of figures with non-empty captions.
        figures_skipped: Number of figures without captions.
    """

    captions: list[FigureCaption] = field(default_factory=list)
    total_token_cost: int = 0
    api_calls_made: int = 0

    @property
    def figures_captioned(self) -> int:
        return sum(1 for c in self.captions if c.has_caption)

    @property
    def figures_skipped(self) -> int:
        return sum(1 for c in self.captions if not c.has_caption)


# ---------------------------------------------------------------------------
# Prompt templates per figure type
# ---------------------------------------------------------------------------

_FIGURE_TYPE_PROMPTS: dict[str, str] = {
    "study_design": (
        "Describe this clinical trial study design diagram. "
        "Extract: treatment arms, randomization ratio, blinding, "
        "stratification factors, crossover points (if any), and "
        "the overall flow from screening to follow-up."
    ),
    "consort": (
        "Describe this CONSORT/patient flow diagram. Extract: "
        "number screened, number randomized, number per arm, "
        "reasons for exclusion/discontinuation, and number "
        "completing the study."
    ),
    "kaplan_meier": (
        "Describe this Kaplan-Meier survival curve. Extract: "
        "endpoints shown, treatment arms, median survival times, "
        "hazard ratios, p-values, and number at risk at key "
        "timepoints."
    ),
    "pk_profile": (
        "Describe this pharmacokinetic profile. Extract: drug "
        "name, sampling timepoints, Cmax, Tmax, AUC values, "
        "half-life, and any dose-proportionality observations."
    ),
    "forest_plot": (
        "Describe this forest plot. Extract: subgroups shown, "
        "hazard ratios or odds ratios with confidence intervals, "
        "overall effect estimate, and heterogeneity statistics."
    ),
    "dose_response": (
        "Describe this dose-response curve. Extract: doses "
        "tested, response metric, EC50/IC50 if shown, and the "
        "shape of the dose-response relationship."
    ),
    "generic": (
        "Describe this clinical trial figure. Identify: what "
        "type of visualization it is, key data points shown, "
        "labels on axes, and any conclusions that can be drawn."
    ),
}


# ---------------------------------------------------------------------------
# Figure captioner
# ---------------------------------------------------------------------------


class FigureCaptioner:
    """Generates captions for detected figures via Vision API.

    Sends cropped figure images to Claude Sonnet Vision API with
    figure-type-specific prompts. Batches figures on the same page
    into a single API call when possible.

    Args:
        model: Anthropic model ID (must support vision).
        scale: Rendering scale for cropped images (2.0 = 144 DPI).
    """

    def __init__(
        self,
        model: str = _DEFAULT_MODEL,
        scale: float = 2.0,
    ) -> None:
        self._model = model
        self._scale = scale
        self._client: Any = None

    def _get_client(self) -> Any:
        """Lazy-init the Anthropic client."""
        if self._client is not None:
            return self._client

        api_key = os.environ.get("ANTHROPIC_API_KEY", "")
        if not api_key:
            return None

        import anthropic
        self._client = anthropic.Anthropic(api_key=api_key)
        return self._client

    def caption_figures(
        self,
        figures: list[DetectedFigure],
        pdf_bytes: bytes,
    ) -> CaptionResult:
        """Generate captions for all detected figures.

        Figures that already have a caption (from caption heuristic
        in PTCV-225) keep their existing caption without an API call.
        Remaining figures are sent to Vision API.

        Args:
            figures: Detected figures from ``detect_figures()``.
            pdf_bytes: Raw PDF bytes for image cropping.

        Returns:
            CaptionResult with captions and cost metrics.
        """
        result = CaptionResult()

        if not figures:
            return result

        client = self._get_client()

        for figure in figures:
            # Use existing caption if available (no API needed)
            if figure.caption:
                result.captions.append(FigureCaption(
                    figure=figure,
                    caption=figure.caption,
                    from_existing=True,
                ))
                continue

            if client is None:
                # No API key — empty caption, no error
                result.captions.append(FigureCaption(figure=figure))
                continue

            # Crop figure from PDF
            img_bytes = crop_figure_image(
                pdf_bytes, figure, scale=self._scale,
            )
            if img_bytes is None:
                result.captions.append(FigureCaption(figure=figure))
                continue

            # Call Vision API
            caption_text, tokens = self._call_vision(
                img_bytes, figure.figure_type_hint,
            )
            result.api_calls_made += 1
            result.total_token_cost += tokens

            result.captions.append(FigureCaption(
                figure=figure,
                caption=caption_text,
                caption_model=self._model,
                token_cost=tokens,
            ))

        return result

    def _call_vision(
        self,
        image_bytes: bytes,
        figure_type: str,
    ) -> tuple[str, int]:
        """Send an image to Vision API for captioning.

        Args:
            image_bytes: PNG bytes of the cropped figure.
            figure_type: Type hint for prompt selection.

        Returns:
            Tuple of (caption_text, token_cost).
        """
        prompt = _FIGURE_TYPE_PROMPTS.get(
            figure_type,
            _FIGURE_TYPE_PROMPTS["generic"],
        )

        system = (
            "You are a clinical trial protocol analyst. "
            "Describe the visual element concisely, extracting "
            "structured information relevant to protocol design "
            "and regulatory review. This is a read-only analysis "
            "of publicly available clinical trial documents."
        )

        b64 = base64.b64encode(image_bytes).decode("utf-8")

        content = [
            {
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": "image/png",
                    "data": b64,
                },
            },
            {"type": "text", "text": prompt},
        ]

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=_MAX_TOKENS,
                system=system,
                messages=[{"role": "user", "content": content}],
            )

            caption = ""
            for block in response.content:
                if block.type == "text":
                    caption = block.text

            tokens = (
                response.usage.input_tokens
                + response.usage.output_tokens
            )

            return caption, tokens

        except Exception as exc:
            logger.warning("Vision captioning failed: %s", exc)
            return "", 0


__all__ = [
    "FigureCaption",
    "FigureCaptioner",
    "CaptionResult",
]
